### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/basil-cli-compiler#259]
- [x] webignition/base-basil-test-case#119
- [x] webignition/basil-compilable-source#420
- [x] webignition/basil-compiler-models#36
- [x] webignition/basil-loader#461
- [x] webignition/basil-models#180
- [x] webignition/php-basil-compilable-source-factory#586
- [x] webignition/single-command-application-factory#5
- [x] webignition/stubble#38
- [x] webignition/symfony-console-typed-input#24
- [x] webignition/basil-data-validator#70
- [x] webignition/basil-parser#105
- [x] webignition/object-reflector#5
- [x] webignition/symfony-panther-webserver-runner#17
